/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface DeepgramWidget {
        "clientToken": string;
    }
}
declare global {
    interface HTMLDeepgramWidgetElement extends Components.DeepgramWidget, HTMLStencilElement {
    }
    var HTMLDeepgramWidgetElement: {
        prototype: HTMLDeepgramWidgetElement;
        new (): HTMLDeepgramWidgetElement;
    };
    interface HTMLElementTagNameMap {
        "deepgram-widget": HTMLDeepgramWidgetElement;
    }
}
declare namespace LocalJSX {
    interface DeepgramWidget {
        "clientToken"?: string;
    }
    interface IntrinsicElements {
        "deepgram-widget": DeepgramWidget;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "deepgram-widget": LocalJSX.DeepgramWidget & JSXBase.HTMLAttributes<HTMLDeepgramWidgetElement>;
        }
    }
}
