/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    /**
     * The Deepgram Widget component.
     * @see https://github.com/deepgram/browser-agent
     */
    interface DeepgramWidget {
        /**
          * The agent client ID.
         */
        "agentClientId": string;
    }
}
declare global {
    /**
     * The Deepgram Widget component.
     * @see https://github.com/deepgram/browser-agent
     */
    interface HTMLDeepgramWidgetElement extends Components.DeepgramWidget, HTMLStencilElement {
    }
    var HTMLDeepgramWidgetElement: {
        prototype: HTMLDeepgramWidgetElement;
        new (): HTMLDeepgramWidgetElement;
    };
    interface HTMLElementTagNameMap {
        "deepgram-widget": HTMLDeepgramWidgetElement;
    }
}
declare namespace LocalJSX {
    /**
     * The Deepgram Widget component.
     * @see https://github.com/deepgram/browser-agent
     */
    interface DeepgramWidget {
        /**
          * The agent client ID.
         */
        "agentClientId"?: string;
    }
    interface IntrinsicElements {
        "deepgram-widget": DeepgramWidget;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            /**
             * The Deepgram Widget component.
             * @see https://github.com/deepgram/browser-agent
             */
            "deepgram-widget": LocalJSX.DeepgramWidget & JSXBase.HTMLAttributes<HTMLDeepgramWidgetElement>;
        }
    }
}
